import React from 'react'

export const metadata = {
    title: "userss",
    description: "Generated by create next app",
  };

function page() {
  return (
    
    
    <div>sda</div>

    
  )
}

export default page